### ISSUE TITLE
Terrain collision

### ISSUE THREAD

**Issue by Juris3D** [vmartsynovskyy/TerrainGen#1]
Please how to enable generated terrain collision

**Comment by vmartsynovskyy** [comment]
In ProceduralTerrain.cpp set the "false" to "true" in the call to procMesh->CreateMeshSection_LinearColor

Let me know if you have any other questions. I didn't think anyone else would be using this :D

**Comment by Juris3D** [comment]
Will try that and recompile, thank you. You could mail me :) juris@datorburvis.lv i could show my UE4 hobby and why i like procedural terrains. Can that collision option be exposed to editor maybe?

**Comment by vmartsynovskyy** [comment]
I can't work on the project for a while because I don't have my windows PC so unfortunately I can't expose it to the editor. Fair warning though, the performance is pretty bad with collisions on.
