### ISSUE TITLE
Errors at loading

### ISSUE THREAD

**Issue by ghost** [vmartsynovskyy/TerrainGen#2]
project is not working, black screen and no terrain present, two errore at loading:

1st Error: Missing TerrainGen Modules / Would you like to rebuild them now?

after rebuilding:

2nd Error: Failed to load map!
/mypath/TerrainGen-master/TerrainGen-master/Content/MyLevel.umap appears to be an asset file.

**Comment by vmartsynovskyy** [comment]
I couldn't reproduce your error unfortunately. I can tell you what I did to build the project from scratch through:

1. `git clone https://github.com/vmartsynovskyy/TerrainGen.git`
2. Open the .uproject file with Unreal Engine
3. Click ok when it asks to rebuild the modules
4. After its done click the play button at the top, making sure that the loaded level is `MyLevel.umap`

I'm doing all of this on Unreal Engine 4.21.2 and Visual Studio 2017 15.9.7 on Windows 10.

If the steps I gave you don't work could you give me the versions of Unreal Engine, Visual Studio, and what OS you are using?

**Comment by ghost** [comment]
the problem is that the level named MyLevel.umap
appear to be like an asset and not a level map

**2nd Error: Failed to load map!
/mypath/TerrainGen-master/TerrainGen-master/Content/MyLevel.umap appears to be an asset file.**

**Comment by ghost** [comment]
I'm on UE 4.21.2 on Windows 10

**Comment by vmartsynovskyy** [comment]
Hmm I looked into it a bit more online and it seems like it might have to do with Git LFS which is what I'm using to store the umap file, but the weird part is that I can pull it from scratch on my machine just fine.

My output for the command `git lfs version` is `git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)`. Could you check the output of that command yourself and if your git-lfs version is lower try updating Git and then cloning again to see if it makes a difference.

**Comment by shiningbroccoli** [comment]
mine is git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
but still can't download a working version

**Comment by ghost** [comment]
Finally get to work! 
Is it normal I don't get any terrain preview since I don't go to play mode?

**Comment by vmartsynovskyy** [comment]
Glad you got it working. What did you do differently that made it work?

And yeah it's normal.
